# Generated by Django 5.2.14 on 2026-06-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='years_of_experience',
            field=models.FloatField(default=0),
        ),
    ]
