# Generated by Django 5.2.14 on 2026-07-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_alter_editor_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
